from django.urls import path
from leave_manager import views as leave_manager_views

urlpatterns = [
    path('', leave_manager_views.get_dashboard, name='leave_manager_dashboard'),
    path('me', leave_manager_views.get_my_profile, name='leave_manager_my_profile'),
    path('users', leave_manager_views.get_users, name='leave_manager_users'),
    # path('notifications', leave_manager_views.get_notifications, name='leave_manager_notifications'),
    path('leaves', leave_manager_views.get_leave_today, name='leave_manager_leave_today'),
    path('leaveRequests', leave_manager_views.get_leave_requests, name='leave_manager_leave_requests'),
    path('leaveRequests/leave/<int:id>', leave_manager_views.get_leave_requests_by_id, name='leave_manager_leave_requests_by_id'),
    path('leaveRequests/compensationLeave/<int:id>', leave_manager_views.leave_manager_compensationLeave_requests_by_id, name='leave_manager_compensationLeave_requests_by_id'),
    path('applyLeave', leave_manager_views.apply_leave, name='leave_manager_apply_leave'),
    path('applyLeave/compensation', leave_manager_views.apply_compensationLeave, name='leave_manager_apply_compensationLeave'),
    path('birthdays', leave_manager_views.get_birthday_today, name='leave_manager_get_birthday_today'),
    path('report', leave_manager_views.generate_report, name="leave-report"),
    path('compensationReport', leave_manager_views.generate_compensationReport, name="compensation-report"),
    path('report/<int:id>',leave_manager_views.report_details, name="report-details"),
    path("leave-history", leave_manager_views.leaveHistory, name="leave-history"),
    path('detail/<int:id>', leave_manager_views.leave_detail, name="leave-detail"),
    path('compensationDetail/<int:id>', leave_manager_views.compensationLeave_detail, name="compensationLeave-detail"),
    path("phone/<int:id>", leave_manager_views.change_user_number, name="change-number"),
    path("photo-crop/<int:id>", leave_manager_views.crop_user_photo, name="crop-photo"),
    path("photo-edit/<int:id>", leave_manager_views.edit_user_photo, name="change-photo"),
    path("holidays/",leave_manager_views.generate_holidays, name="company-holiday"),
    path("holidays/add", leave_manager_views.add_new_holidays, name="add-holidays"),
    path("holidays/edit/<int:id>", leave_manager_views.update_company_holidays_by_id, name="holidays-edit"),
    path("holidays/delete/<int:id>", leave_manager_views.delete_company_holidays_by_id, name="holidays-delete"),
    path("leaveRequests/notify/", leave_manager_views.notify, name="notify"),
    path("rhymes/", leave_manager_views.generate_rhymes, name="rhymes"),
    path("rhymes/add-rhymes/", leave_manager_views.add_new_rhymes, name="add-rhymes"),
    path("rhymes/edit/<int:id>", leave_manager_views.update_rhyme_by_id, name="rhymes-edit"),
    path("rhymes/delete/<int:id>", leave_manager_views.delete_rhyme_by_id, name="rhymes-delete"),
    path("rhymeTypes/", leave_manager_views.generate_rhymeTypes, name="rhymeTypes"),
    path("rhymeTypes/add-rhymeTypes/", leave_manager_views.add_new_rhymeType, name="add-rhymeType"),
    path("rhymeTypes/edit/<int:id>", leave_manager_views.update_rhymeTypes_by_id, name="rhymeType-edit"),
    path("rhymeTypes/delete/<int:id>", leave_manager_views.delete_rhymeTypes_by_id, name="rhymeType-delete"),
    path("generate-report-byPerson/<int:id>",leave_manager_views.generate_report_byPerson,name="generate-report-byPerson")
]
